version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - FRONTEND_URL=http://frontend:3001
      - NODE_ENV=production
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_BACKEND_URL=http://backend:3000
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend 