services:
  - type: web
    name: codeviz-backend
    runtime: docker
    repo: https://github.com/OmerEfron/code-vis
    region: oregon # Or choose a region closer to you
    plan: free
    healthCheckPath: /api/health
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: https://codeviz.vercel.app # This will be your Vercel URL
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        fromSecret: true 